version: '3.8'

services:
  fastify-db:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: always # reinicia automáticamente quando acontece algum erro
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local